replicaCount: 1

image:
  repository: skybyte/app
  tag: latest
  pullPolicy: Always

namespace: devops-challenge

containerPort: 80

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10

  readiness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10

prometheus:
  enabled: true
  path: /metrics
  port: "80"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000